spring:
  application:
    name: demo

app:
  fb:
    page-id: ${FB_PAGE_ID:681857498348124}
    access-token: 
    api-version: 
    fetch-interval-seconds: 

google:
  sheetId: ${GOOGLE_SHEET_ID:}
  range: ${GOOGLE_SHEET_RANGE:Sheet1!A:G}
